import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { QueryClientProviderWrapper } from "@/components/query-client-provider-wrapper"
import { TopBar } from "@/components/top-bar"
import { BottomNavigation } from "@/components/bottom-navigation"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Movie book series app",
  description: "Generated by create next app",
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.className)}>
        <QueryClientProviderWrapper>
          <TopBar />
          <main className="flex-1">{children}</main>
          <BottomNavigation />
        </QueryClientProviderWrapper>
      </body>
    </html>
  )
}
