spring:
  profiles:
    active: dev
  application:
    name: Catalog Service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ReviewIt}"
          principal-claim-name: preferred_username
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:catalogdb}

tmdb:
  api-key: ${TMDB_API_KEY:your_tmdb_api_key_here}

google:
  books:
    api-key: ${GOOGLE_API_KEY:your_google_api_key_here}

server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    path: /swagger

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
