spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/socialdb}
    username: ${DB_USER:socialuser}
    password: ${DB_PASS:socialpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: false