spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/socialdb}
    username: ${DB_USER:socialuser}
    password: ${DB_PASS:socialpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update    # <-- crea/actualiza tablas en dev
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false        # <-- desactiva Flyway mientras no tengas migraciones
