networks:
  web:
    name: project_web
    driver: bridge
  app:
    name: project_app
    driver: bridge
    internal: true
  egress: # Egress network for external access
    name: project_egress
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
  pgdata:
  reviews_pgdata:
  mongodb_data:

services:
  # -------- REVERSE PROXY + TLS ----------
  caddy:
    image: caddy:2.8
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/Madrid
      - ACME_AGREE=true
      - GATEWAY_PORT=${GATEWAY_PORT}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [web, app]
    depends_on:
      gateway:
        condition: service_healthy
      keycloak:
        condition: service_started
      frontend:
        condition: service_healthy

  # -------- FRONTEND (opcional, añade host si lo usarás) ----------
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        NEXTJS_PORT: 3000
    env_file:
      - front/.env.production
    restart: unless-stopped
    networks: [app]

  # -------- GATEWAY ----------
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        GATEWAY_PORT: "${GATEWAY_PORT}"
    env_file:
      - gateway/.env.prod
    depends_on:
      keycloak:
        condition: service_started
      catalog-service:
        condition: service_healthy
    restart: unless-stopped
    networks: [app]

  # -------- KEYCLOAK + DB ----------
  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks: [app]
  keycloak:
    build:
      context: ./keycloak-image
      dockerfile: Containerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/authdb"
      KC_DB_USERNAME: authuser
      KC_DB_PASSWORD: authpass
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: ["start", "--optimized", "--import-realm"]
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks: [app]

  # -------- CATALOG (Mongo + servicio) ----------
  catalog-db:
    image: mongo:8
    command: ["--wiredTigerCacheSizeGB","1"]
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL","mongosh --quiet --eval 'db.adminCommand({ ping: 1 }).ok' | grep -q 1 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 15
    restart: unless-stopped
    networks: [app]

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
      args:
        CATALOG_SERVICE_PORT: "${CATALOG_SERVICE_PORT}"
    env_file:
      - catalog-service/.env.prod
    environment:
      SERVER_PORT: "${CATALOG_SERVICE_PORT}"
    depends_on:
      catalog-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks: [app, egress]

  # -------- REVIEWS DB ----------
  reviews-db:
    image: postgres:16
    environment:
      POSTGRES_DB: reviewsdb
      POSTGRES_USER: reviewsuser
      POSTGRES_PASSWORD: reviewspass
    volumes:
      - reviews_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reviewsuser -d reviewsdb"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks: [app]

  # -------- RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [app]
