services:
  auth-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
          POSTGRES_DB: authdb
          POSTGRES_USER: authuser
          POSTGRES_PASSWORD: authpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
