# Containerfile Keycloak (sin instalar nada adicional)
FROM quay.io/keycloak/keycloak:24.0.1 AS builder
ENV KC_HEALTH_ENABLED=true KC_METRICS_ENABLED=true KC_DB=postgres
WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:24.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/
CMD ["start","--optimized","--hostname-strict=false"]
