spring:
  application:
    name: Social Service
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ReviewIt}"
          jwk-set-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ReviewIt}/protocol/openid-connect/certs"
          principal-claim-name: preferred_username

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/socialdb}
    username: ${DB_USER:socialuser}
    password: ${DB_PASS:socialpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20

server:
  port: ${SERVER_PORT:8082}

keycloak:
  url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:ReviewIt}
  admin:
    client-id: ${KC_ADMIN_CLIENT_ID:admin-service}
    client-secret: ${KC_ADMIN_CLIENT_SECRET:changeme}
  users:
    default-max: 50

catalog:
  url: ${CATALOG_BASE_URL:http://localhost:8081}
