spring:
  application:
    name: Social Service
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ReviewIt}"
          jwk-set-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:ReviewIt}/protocol/openid-connect/certs"
          principal-claim-name: preferred_username
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/socialdb}
    username: ${DB_USER:socialuser}
    password: ${DB_PASS:socialpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc.time_zone: UTC

server:
  port: ${SERVER_PORT:8082}
