spring:
  application:
    name: Gateway API

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/TrustedFeedbackGateway}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/TrustedFeedbackGateway/protocol/openid-connect/certs}
          principal-claim-name: ${KEYCLOAK_PRINCIPAL_CLAIM:preferred_username}

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
          routes:
            - id: catalog-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/catalog/**
            - id: keycloak
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

server:
  port: ${SERVER_PORT:8000}
