spring:
  application:
    name: Gateway API

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:TrustedFeedbackGateway}"
          jwk-set-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:TrustedFeedbackGateway}/protocol/openid-connect/certs"
          principal-claim-name: preferred_username

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - RemoveRequestHeader=Cookie
          routes:
            - id: catalog-service
              uri: ${CATALOG_API_URL:http://localhost:8081}
              predicates:
                - Path=/api/catalog/**
            - id: keycloak
              uri: ${KEYCLOAK_BASE_URL:http://localhost:8080}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

server:
  port: ${SERVER_PORT:8000}
